import Container from './layout/container'
import Header from './layout/header'
import Body, { BodyAlignedBotton } from './layout/body'
import { Footer } from './layout/footer'

export const Layout = { Container, Header, Body, BodyAlignedBotton, Footer }

export * from './controls/toggle/Toggle'
export * from './items'
export * from './shared-components/UnifiedText'
export * from './modal'
export * from './button'
export * from './input'
export * from './list'
export * from './templates'
export * from './NewVaultForm'
export * from './SetupPassForm'
export * from './alert'
export * from './utils'
export * from './WelcomeSlide'
export * from './hero'
export * from './seed-input'
export * from './vault'
export * from './ActionItem'
export * from './SafeAreaView'
export * from './form'

export { NetworkFormType } from './NetworkForm'

export { default as ActivityIndicator } from './ActivityIndicator'
export { default as TextCopy } from './text/text-copy'
export { default as ModalHeader } from './modal/ModalHeader'
export { default as ModalContent } from './modal/ModalContent'
export { default as NetworkListItem2 } from './change-network/network-list-item'
export { default as Icons } from './icons'
export { default as ErrorBox } from './ErrorBox'

export { OnboardingCarousel } from './OnboardingCarousel'
export { OnboardingFooter } from './OnboardingFooter'
export { WelcomeBackFooter } from './WelcomeBackFooter'
export { NetworkSelectionModal } from './NetworkSelectionModal'
export { NetworkButtonModal } from './NetworkButtonModal'
export { BetaVersionMiniBanner, BetaVersionHeader } from './BetaVersionBanner'
export { NetworkForm } from './NetworkForm'
export { LoadingModal, Loading } from './loading'
